// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ResourceRole.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ResourceRole.proto</summary>
public static partial class ResourceRoleReflection {

  #region Descriptor
  /// <summary>File descriptor for ResourceRole.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ResourceRoleReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChJSZXNvdXJjZVJvbGUucHJvdG8qGwoMUmVzb3VyY2VSb2xlEgsKB1RleHR1",
          "cmUQAGIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ResourceRole), }, null, null));
  }
  #endregion

}
#region Enums
public enum ResourceRole {
  [pbr::OriginalName("Texture")] Texture = 0,
}

#endregion


#endregion Designer generated code
